### ISSUE TITLE
In part 5 , how the state dimension is 9 ?

### ISSUE THREAD

**Issue by Sarthak-02** [MorvanZhou/train-robot-arm-from-scratch#1]
on what basis do you define the state dimension ?

**Comment by MorvanZhou** [comment]
The state should be the observations that are unique and representative in the current circumstance.

**Comment by Sarthak-02** [comment]
I am sorry ,I am new to this , so maybe these are very naive questions to you ,but how are you observing the state dimension , if i have to increase the number of arms, how would it effect the state dimension in this programme ?

**Comment by MorvanZhou** [comment]
There are many ways to determine the number of observations. For example the xy distance to the goal, the rotation angle and so on. As long as the state or observation is representative and helpful in finding the goal, it may beneficial to the agent.
