### ISSUE TITLE
done判断条件疑问

### ISSUE THREAD

**Issue by asd51731** [MorvanZhou/train-robot-arm-from-scratch#4]
你好， 看了你的程序，感觉env中的done判断条件如part5中，43行的else是否应该对应38行的if啊？

**Comment by MorvanZhou** [comment]
是的，有问题，谢谢提醒，我[重写了一下](https://github.com/MorvanZhou/train-robot-arm-from-scratch/blob/master/part5/env.py#L38)，总体意思是说，如果落在方框内 `r+=1, on_goal+=1`,如果连续50步都在方框里, 就done=True, 只要有移出方框，计数都要重来。
